import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Sidebar Configuration
 *
 * Using auto-generated sidebar from the docs folder structure.
 *
 * How ordering works:
 * 1. Folders use _category_.json with "position" field
 * 2. Docs use frontmatter "sidebar_position" field
 * 3. Lower numbers appear higher in sidebar
 */
const sidebars: SidebarsConfig = {
  // Auto-generate sidebar from docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
